import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

export const dynamic = 'force-dynamic';
import { AuthProviderWrapper } from '@/components/providers/AuthProviderWrapper';
import { QueryProviders } from '@/components/providers/QueryProviders';
import { Toaster } from '@/components/ui/sonner';
import { ModalProvider } from '@/components/providers/ModalProvider';
import { GlobalModal } from '@/components/GlobalModal';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProviders>
          <ModalProvider>
            <AuthProviderWrapper>
              {children}
              <GlobalModal />
            </AuthProviderWrapper>
          </ModalProvider>
        </QueryProviders>
        <Toaster />
      </body>
    </html>
  );
}
